name: burtone
description: A client management app for Burtone Solutions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_core_web: ^2.5.0
  firebase_auth: ^4.6.2
  firebase_auth_web: ^5.5.2
  cloud_firestore: ^4.7.1
  cloud_firestore_web: ^3.5.1
  firebase_storage: ^11.2.2
  firebase_storage_web: ^3.6.2
  provider: ^6.0.5
  intl: ^0.19.0
  image_picker: ^0.8.7
  image_picker_web: ^3.0.0+1
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  js: ^0.6.7
  http: ^1.1.0
  web: ^0.1.4-beta
  js_interop: ^0.0.1
  device_preview: ^1.1.0
  flutter_platform_widgets: ^3.3.5
  salomon_bottom_bar: ^3.3.2
  fl_chart: ^0.63.0
  csv: ^5.0.2
  share_plus: ^7.0.2
  google_fonts: ^4.0.4
  flutter_animate: ^4.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  google_sign_in: ^6.1.4
  googleapis: ^11.2.0
  file_picker: ^5.3.2
  shared_preferences: ^2.1.2
  excel: ^2.1.0
  mime: ^1.0.4
  enough_mail: ^2.1.1
  pdf: ^3.10.1
  sqflite: ^2.2.8+4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logosma.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logosma.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/african_print.png
    - assets/images/client.png
    - assets/images/logosma.png
